<template>
  <el-dialog
    v-model="isVisible"
    :title="$t(isEditing ? 'resource.editAgencyTitle' : 'resource.createAgencyTitle')"
    width="600px"
    destroy-on-close
    @closed="resetForm"
  >
    <el-form
      ref="formRef"
      :model="form"
      :rules="rules"
      label-width="auto"
    >
      <el-form-item :label="$t('resource.code')">
        <el-input
          v-model="form.code"
          :placeholder="$t('resource.codeAutoGenerated')"
          disabled
        />
      </el-form-item>
      <el-form-item
        :label="$t('resource.agencyName')"
        prop="name"
      >
        <el-input v-model.trim="form.name" />
      </el-form-item>
      <el-form-item
        :label="$t('resource.countryOrRegion')"
        prop="countryOrRegion"
      >
        <el-input v-model.trim="form.countryOrRegion" />
      </el-form-item>
      <el-form-item :label="$t('resource.city')">
        <el-input v-model.trim="form.city" />
      </el-form-item>
      <el-form-item
        :label="$t('resource.agencyEmail')"
        prop="email"
      >
        <el-input v-model.trim="form.email" />
      </el-form-item>
      <el-form-item :label="$t('common.remark')">
        <el-input
          v-model.trim="form.remark"
          type="textarea"
          :rows="3"
        />
      </el-form-item>
      <el-form-item :label="$t('common.status')">
        <el-radio-group v-model="form.status">
          <el-radio value="enabled">
            {{ $t("common.enabled") }}
          </el-radio>
          <el-radio value="disabled">
            {{ $t("common.disabled") }}
          </el-radio>
        </el-radio-group>
      </el-form-item>
    </el-form>
    <template #footer>
      <el-button @click="isVisible = false">
        {{ $t("common.cancel") }}
      </el-button>
      <el-button
        type="primary"
        @click="handleSubmit"
      >
        {{ $t("common.confirm") }}
      </el-button>
    </template>
  </el-dialog>
</template>

<script setup lang="ts">
import { computed, reactive, ref, watch } from "vue";
import type { FormInstance, FormRules } from "element-plus";
import { useI18n } from "vue-i18n";
import type { AgencyRecord } from "@/types/resource";

const props = defineProps<{
  modelValue: boolean;
  record: AgencyRecord;
  isEditing: boolean;
}>();

const emit = defineEmits<{
  "update:modelValue": [value: boolean];
  submit: [record: AgencyRecord];
}>();

const { t } = useI18n();
const formRef = ref<FormInstance>();
const form = reactive<AgencyRecord>(cloneRecord(props.record));
const isVisible = computed({ get: () => props.modelValue, set: (value) => emit("update:modelValue", value) });
const rules = computed<FormRules>(() => ({
  name: [{ required: true, message: t("resource.fieldRequired", { field: t("resource.agencyName") }), trigger: "blur" }],
  countryOrRegion: [{ required: true, message: t("resource.fieldRequired", { field: t("resource.countryOrRegion") }), trigger: "blur" }],
  email: [{ required: true, message: t("resource.fieldRequired", { field: t("resource.agencyEmail") }), trigger: "blur" }],
}));

watch(() => props.record, (record) => Object.assign(form, cloneRecord(record)), { deep: true });

function cloneRecord(record: AgencyRecord): AgencyRecord {
  return { ...record, contacts: record.contacts.map((contact) => ({ ...contact })) };
}

function resetForm() {
  formRef.value?.clearValidate();
}

async function handleSubmit() {
  if (!(await formRef.value?.validate().catch(() => false))) return;
  emit("submit", cloneRecord(form));
}
</script>
