<template>
  <div class="page-container">
    <el-card
      class="page-search"
      shadow="never"
    >
      <el-form :inline="true">
        <el-form-item :label="$t('common.keywords')">
          <el-input
            v-model.trim="keywords"
            :placeholder="$t('resource.searchPlaceholder')"
            clearable
          />
        </el-form-item>
        <el-form-item>
          <el-button
            type="primary"
            @click="resetPage"
          >
            {{ $t("common.search") }}
          </el-button>
          <el-button @click="resetQuery">
            {{ $t("common.reset") }}
          </el-button>
        </el-form-item>
      </el-form>
    </el-card>

    <el-card
      class="page-content"
      shadow="never"
    >
      <div class="page-toolbar">
        <div class="page-toolbar__left">
          <el-button
            type="primary"
            @click="openCreateDialog"
          >
            {{ $t("common.create") }}
          </el-button>
        </div>
      </div>
      <div class="page-table-wrapper">
        <el-table
          :data="pagedList"
          border
          height="100%"
        >
          <el-table-column
            prop="code"
            :label="$t('resource.code')"
            min-width="120"
          />
          <el-table-column
            prop="name"
            :label="$t('resource.name')"
            min-width="180"
          />
          <el-table-column
            prop="city"
            :label="$t('resource.city')"
            min-width="120"
          />
          <el-table-column
            prop="contact"
            :label="$t('resource.contact')"
            min-width="130"
          />
          <el-table-column
            prop="phone"
            :label="$t('resource.phone')"
            min-width="140"
          />
          <el-table-column
            :label="$t('common.status')"
            width="100"
            align="center"
          >
            <template #default="scope">
              <el-tag :type="scope.row.status === 'enabled' ? 'success' : 'info'">
                {{ $t(`common.${scope.row.status}`) }}
              </el-tag>
            </template>
          </el-table-column>
          <el-table-column
            :label="$t('common.actions')"
            width="180"
            align="center"
            fixed="right"
          >
            <template #default="scope">
              <el-button
                type="primary"
                link
                @click="openEditDialog(scope.row as TourismResourceRecord)"
              >
                {{ $t("common.edit") }}
              </el-button>
              <el-button
                type="warning"
                link
                @click="toggleStatus(scope.row as TourismResourceRecord)"
              >
                {{ $t(scope.row.status === "enabled" ? "common.disabled" : "common.enabled") }}
              </el-button>
            </template>
          </el-table-column>
        </el-table>
      </div>
      <pagination
        v-if="filteredList.length"
        v-model:total="total"
        v-model:page="pageNum"
        v-model:limit="pageSize"
      />
    </el-card>

    <el-dialog
      v-model="isDialogVisible"
      :title="$t(isEditing ? 'resource.editTitle' : 'resource.createTitle')"
      width="560px"
      @closed="resetForm"
    >
      <el-form
        ref="formRef"
        :model="form"
        :rules="rules"
        label-width="110px"
      >
        <el-form-item
          :label="$t('resource.code')"
        >
          <el-input
            v-model="form.code"
            :placeholder="$t('resource.codeAutoGenerated')"
            disabled
          />
        </el-form-item>
        <el-form-item
          :label="$t('resource.name')"
          prop="name"
        >
          <el-input v-model.trim="form.name" />
        </el-form-item>
        <el-form-item :label="$t('resource.city')">
          <el-input v-model.trim="form.city" />
        </el-form-item>
        <el-form-item :label="$t('resource.contact')">
          <el-input v-model.trim="form.contact" />
        </el-form-item>
        <el-form-item :label="$t('resource.phone')">
          <el-input v-model.trim="form.phone" />
        </el-form-item>
        <el-form-item :label="$t('common.status')">
          <el-radio-group v-model="form.status">
            <el-radio value="enabled">
              {{ $t("common.enabled") }}
            </el-radio><el-radio value="disabled">
              {{ $t("common.disabled") }}
            </el-radio>
          </el-radio-group>
        </el-form-item>
        <el-form-item :label="$t('common.remark')">
          <el-input
            v-model.trim="form.remark"
            type="textarea"
            :rows="3"
          />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="isDialogVisible = false">
          {{ $t("common.cancel") }}
        </el-button><el-button
          type="primary"
          @click="handleSubmit"
        >
          {{ $t("common.confirm") }}
        </el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, reactive, ref, watch } from "vue";
import type { FormInstance, FormRules } from "element-plus";
import { ElMessage } from "element-plus";
import { useI18n } from "vue-i18n";
import { useRoute } from "vue-router";
import { tourismResources, type TourismResourceRecord, type TourismResourceType } from "@/data/data";

const route = useRoute();
const { t } = useI18n();
const formRef = ref<FormInstance>();
const keywords = ref("");
const pageNum = ref(1);
const pageSize = ref(10);
const isDialogVisible = ref(false);
const editingId = ref("");
const resourceType = computed(() => route.meta.resourceType as TourismResourceType);
const resourceList = computed(() => tourismResources[resourceType.value]);
const isEditing = computed(() => Boolean(editingId.value));
const form = reactive<TourismResourceRecord>(createEmptyForm());
const rules = computed<FormRules>(() => ({
  name: [{ required: true, message: t("resource.nameRequired"), trigger: "blur" }],
}));
const resourceCodePrefixes: Record<TourismResourceType, string> = {
  supplier: "SUP",
  hotel: "HTL",
  restaurant: "RES",
  attraction: "ATT",
  transport: "VEH",
  guide: "GDE",
};
const filteredList = computed(() => {
  const value = keywords.value.toLowerCase();
  if (!value) return resourceList.value;
  return resourceList.value.filter((item) => [item.code, item.name, item.city].some((field) => field.toLowerCase().includes(value)));
});
const total = computed({ get: () => filteredList.value.length, set: () => undefined });
const pagedList = computed(() => filteredList.value.slice((pageNum.value - 1) * pageSize.value, pageNum.value * pageSize.value));

watch(resourceType, () => { keywords.value = ""; pageNum.value = 1; });

function createEmptyForm(): TourismResourceRecord {
  return { id: "", code: "", name: "", city: "", contact: "", phone: "", status: "enabled", remark: "" };
}
function resetPage() { pageNum.value = 1; }
function resetQuery() { keywords.value = ""; pageNum.value = 1; }
function resetForm() { Object.assign(form, createEmptyForm()); editingId.value = ""; formRef.value?.clearValidate(); }
function generateResourceCode() {
  const prefix = resourceCodePrefixes[resourceType.value];
  const maxSequence = resourceList.value.reduce((max, item) => {
    const match = item.code.match(new RegExp(`^${prefix}-(\\d+)$`));
    return match ? Math.max(max, Number(match[1])) : max;
  }, 0);
  return `${prefix}-${String(maxSequence + 1).padStart(3, "0")}`;
}
function openCreateDialog() { resetForm(); form.code = generateResourceCode(); isDialogVisible.value = true; }
function openEditDialog(record: TourismResourceRecord) { editingId.value = record.id; Object.assign(form, record); isDialogVisible.value = true; }
function toggleStatus(record: TourismResourceRecord) { record.status = record.status === "enabled" ? "disabled" : "enabled"; ElMessage.success(t("common.updateSuccess")); }
async function handleSubmit() {
  if (!(await formRef.value?.validate().catch(() => false))) return;
  if (editingId.value) {
    const record = resourceList.value.find((item) => item.id === editingId.value);
    if (record) Object.assign(record, form);
  } else {
    resourceList.value.unshift({ ...form, id: `${resourceType.value}-${Date.now()}` });
  }
  isDialogVisible.value = false;
  ElMessage.success(t(isEditing.value ? "common.updateSuccess" : "common.createSuccess"));
}
</script>
