<template>
  <el-dialog
    v-model="isVisible"
    :title="$t(titleKey)"
    width="560px"
    destroy-on-close
    @closed="resetForm"
  >
    <el-form
      ref="formRef"
      :model="form"
      :rules="rules"
      label-width="auto"
    >
      <el-form-item :label="$t('resource.code')">
        <el-input
          v-model="form.code"
          :placeholder="$t('resource.codeAutoGenerated')"
          disabled
        />
      </el-form-item>
      <el-form-item
        v-for="field in fields"
        :key="field.prop"
        :label="$t(field.labelKey)"
        :prop="field.prop"
      >
        <el-input-number
          v-if="field.type === 'number'"
          :model-value="Number(form[field.prop] ?? 0)"
          :min="0"
          controls-position="right"
          @update:model-value="form[field.prop] = $event ?? 0"
        />
        <el-input
          v-else
          v-model.trim="form[field.prop]"
          :type="field.type === 'textarea' ? 'textarea' : 'text'"
          :rows="3"
        />
      </el-form-item>
      <el-form-item :label="$t('common.status')">
        <el-radio-group v-model="form.status">
          <el-radio value="enabled">
            {{ $t("common.enabled") }}
          </el-radio>
          <el-radio value="disabled">
            {{ $t("common.disabled") }}
          </el-radio>
        </el-radio-group>
      </el-form-item>
    </el-form>
    <template #footer>
      <el-button @click="isVisible = false">
        {{ $t("common.cancel") }}
      </el-button>
      <el-button
        type="primary"
        @click="handleSubmit"
      >
        {{ $t("common.confirm") }}
      </el-button>
    </template>
  </el-dialog>
</template>

<script setup lang="ts">
import { computed, reactive, ref, watch } from "vue";
import type { FormInstance, FormRules } from "element-plus";
import { useI18n } from "vue-i18n";
import type { ResourceFormField, ResourceRow } from "../types";

const props = defineProps<{
  modelValue: boolean;
  record: ResourceRow;
  fields: ResourceFormField[];
  titleKey: string;
}>();

const emit = defineEmits<{
  "update:modelValue": [value: boolean];
  submit: [record: ResourceRow];
}>();

const { t } = useI18n();
const formRef = ref<FormInstance>();
const form = reactive<ResourceRow>({ ...props.record });
const isVisible = computed({ get: () => props.modelValue, set: (value) => emit("update:modelValue", value) });
const rules = computed<FormRules>(() => Object.fromEntries(props.fields.filter((field) => field.required).map((field) => [field.prop, [{ required: true, message: t("resource.fieldRequired", { field: t(field.labelKey) }), trigger: "blur" }]])));

watch(() => props.record, (record) => Object.assign(form, record), { deep: true });

function resetForm() {
  formRef.value?.clearValidate();
}

async function handleSubmit() {
  if (!(await formRef.value?.validate().catch(() => false))) return;
  emit("submit", { ...form });
}
</script>
